

export const STUDIO_CONNECT_CONSTANTS = {
    INVANA_ENGINE_URL: "INVANA_ENGINE_URL",
    HTTP_HEADERS: "HTTP_HEADERS",
    GRAPH_ENGINE_NAME: "GRAPH_ENGINE_NAME",
    RENDERING_EDGES_SETTINGS: "RENDERING_EDGES_SETTINGS"
}