

export const STUDIO_CONNECT_CONSTANTS = {
    INVANA_ENGINE_URL: "INVANA_ENGINE_URL",
    HTTP_HEADERS: "INVANA_HTTP_HEADERS",
    GRAPH_ENGINE_NAME: "INVANA_GRAPH_ENGINE_NAME",
    RENDERING_EDGES_SETTINGS: "INVANA_RENDERING_EDGES_SETTINGS"
}